version: "2"
services:
  backend:
    image: mongo:latest
    ports:
      - '24242:24242'
    networks:
        - docker_cont_network
    command: mongod --port 24242
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8082:8080"
    environment:
      - SWAGGER_JSON=localhost:5000/swagger.json
    networks:
      - docker_cont_network
  swagger-editor:
    image: swaggerapi/swagger-editor
    ports:
      - "8081:8080"
    networks:
      - docker_cont_network
  frontend:
      build: .
      command: python -u app.py
      ports:
        - "5000:5000"
      volumes:
        - .:/app
      links:
        - backend
      networks:
        - docker_cont_network
networks:
  docker_cont_network:
    driver: bridge